"""document write ordering

Revision ID: 0002_seq
Revises: 0001_initial
Create Date: 2026-07-31 22:55:06.883400
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_seq'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('last_client_seq', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'last_client_seq')
    # ### end Alembic commands ###
