"""editor scoped write ordering

Revision ID: 0003_editor
Revises: 0002_seq
Create Date: 2026-07-31 23:28:55.323323
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003_editor'
down_revision: Union[str, None] = '0002_seq'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('last_editor_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'last_editor_id')
    # ### end Alembic commands ###
