"""project name ordering index

Revision ID: 0004_nameidx
Revises: 0003_editor
Create Date: 2026-07-31 23:35:02.824398
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004_nameidx'
down_revision: Union[str, None] = '0003_editor'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_projects_name_id', 'projects', ['name', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_name_id', table_name='projects')
    # ### end Alembic commands ###
